DROP SEQUENCE SYSUSER_ID;
DROP SEQUENCE STARTUP_ID; 
DROP SEQUENCE MAJOR_ID;
DROP SEQUENCE FACULTY_ID;
DROP SEQUENCE PROFILESTATE_ID;
DROP SEQUENCE STARTUPSTATE_ID;
DROP SEQUENCE AVATAR_ID; 
DROP SEQUENCE PROJECTTYPE_ID;
DROP SEQUENCE SKILL_ID; 
DROP SEQUENCE VACANCY_ID; 
DROP SEQUENCE POST_ID; 

CREATE SEQUENCE SYSUSER_ID
  START with 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE SEQUENCE POST_ID
  START with 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE SEQUENCE STARTUP_ID
  START with 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE SEQUENCE FACULTY_ID
  START with 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE SEQUENCE MAJOR_ID
  START with 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE SEQUENCE SKILL_ID
  START with 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

  CREATE SEQUENCE PROJECTTYPE_ID
  START with 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;
  
  CREATE SEQUENCE AVATAR_ID
  START with 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;
  
  CREATE SEQUENCE STARTUPSTATE_ID
  START with 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;
  
  CREATE SEQUENCE PROFILESTATE_ID
  START with 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

  CREATE SEQUENCE VACANCY_ID
  START with 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;
  
  