DROP TRIGGER SYSUSER_TRG;
DROP TRIGGER STARTUP_TRG; 
DROP TRIGGER MAJOR_TRG;
DROP TRIGGER FACULTY_TRG;
DROP TRIGGER PROFILESTATE_TRG;
DROP TRIGGER STARTUPSTATE_TRG;
DROP TRIGGER AVATAR_TRG; 
DROP TRIGGER PROJECTTYPE_TRG;
DROP TRIGGER SKILL_TRG;
DROP TRIGGER VACANCY_TRG;
DROP TRIGGER POST_TRG;


CREATE OR REPLACE TRIGGER SYSUSER_TRG 
BEFORE INSERT ON SYSUSER 
FOR EACH ROW
BEGIN
  SELECT SYSUSER_ID.NEXTVAL
  INTO   :new.ID
  FROM   dual;
END;
/

CREATE OR REPLACE TRIGGER POST_TRG 
BEFORE INSERT ON POST 
FOR EACH ROW
BEGIN
  SELECT POST_ID.NEXTVAL
  INTO   :new.ID
  FROM   dual;
END;
/

CREATE OR REPLACE TRIGGER STARTUP_TRG 
BEFORE INSERT ON STARTUP 
FOR EACH ROW
BEGIN
  SELECT STARTUP_ID.NEXTVAL
  INTO   :new.ID
  FROM   dual;
END;
/

CREATE OR REPLACE TRIGGER MAJOR_TRG 
BEFORE INSERT ON MAJOR 
FOR EACH ROW
BEGIN
  SELECT MAJOR_ID.NEXTVAL
  INTO   :new.ID
  FROM   dual;
END;
/

CREATE OR REPLACE TRIGGER FACULTY_TRG 
BEFORE INSERT ON FACULTY 
FOR EACH ROW
BEGIN
  SELECT FACULTY_ID.NEXTVAL
  INTO   :new.ID
  FROM   dual;
END;
/

CREATE OR REPLACE TRIGGER AVATAR_TRG 
BEFORE INSERT ON AVATAR 
FOR EACH ROW
BEGIN
  SELECT AVATAR_ID.NEXTVAL
  INTO   :new.ID
  FROM   dual;
END;
/

CREATE OR REPLACE TRIGGER SKILL_TRG 
BEFORE INSERT ON SKILL 
FOR EACH ROW
BEGIN
  SELECT SKILL_ID.NEXTVAL
  INTO   :new.ID
  FROM   dual;
END;
/

CREATE OR REPLACE TRIGGER PROFILESTATE_TRG 
BEFORE INSERT ON PROFILESTATE 
FOR EACH ROW
BEGIN
  SELECT PROFILESTATE_ID.NEXTVAL
  INTO   :new.ID
  FROM   dual;
END;
/

CREATE OR REPLACE TRIGGER STARTUPSTATE_TRG 
BEFORE INSERT ON STARTUPSTATE 
FOR EACH ROW
BEGIN
  SELECT STARTUPSTATE_ID.NEXTVAL
  INTO   :new.ID
  FROM   dual;
END;
/

CREATE OR REPLACE TRIGGER PROJECTTYPE_TRG 
BEFORE INSERT ON PROJECTTYPE 
FOR EACH ROW
BEGIN
  SELECT PROJECTTYPE_ID.NEXTVAL
  INTO   :new.ID
  FROM   dual;
END;
/

CREATE OR REPLACE TRIGGER VACANCY_TRG 
BEFORE INSERT ON VACANCY 
FOR EACH ROW
BEGIN
  SELECT VACANCY_ID.NEXTVAL
  INTO   :new.ID
  FROM   dual;
END;
/
